export default {
  MOVIES: "MOVIES",
  CURRENT_PAGE: "CURRENT_PAGE",
  TOGGLE_LOADER: "TOGGLE_LOADER",
  REMOVE_MOVIE: "REMOVE_MOVIE",
  TOGGLE_SEARCH: "TOGGLE_SEARCH",
  SHOW_TOAST_NOTIFY: "SHOW_TOAST_NOTIFY",
  ADD_NEW_MOVIE: "ADD_NEW_MOVIE",
  EDIT_MOVIE: "EDIT_MOVIE",
  ADD_CUSTOM_FILM: "ADD_CUSTOM_FILM",
};
